### ISSUE TITLE
Problem finding files.

### ISSUE THREAD

**Issue by SimonGoring** [SimonGoring/clam#1]
Some of the calibration files need to be changed to RData files so that they can be loaded as data.
For example, the command:
`calibrate(cage=270, error=30)`
returns an error:

```
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'IntCal13.14C': No such file or directory
```

Should be a fairly simple fix.

**Comment by verkator** [comment]
Just put the file (e.g. 'IntCal13.14C') into the working directory.
